### ISSUE TITLE
Criar Persona de Usuários do Ecoa Estágios

### ISSUE THREAD

**Issue by antunes-neto** [antunes-neto/24.1_PPTI#13]
usar plataformas online como o MIRO ou o GERADORDEPERSONAS para criar uma PERSONA para casa usuário mapeado.

**Comment by Yuri357** [comment]
[page_7662_638487662972811362.pdf](https://github.com/antunes-neto/24.1_PPTI/files/14979617/page_7662_638487662972811362.pdf)
